FROM node:24-slim AS dev-dep-env
COPY /frontend/ /app/
WORKDIR /app
RUN npm ci

FROM node:24-slim AS prod-dep-env
COPY /frontend/package.json /frontend/package-lock.json /app/
WORKDIR /app
RUN npm ci --omit=dev

FROM node:24-slim AS build-env
COPY /frontend/ /app/
COPY --from=dev-dep-env /app/node_modules /app/node_modules
WORKDIR /app
ARG HOST
ARG BACKEND_PORT
ENV VITE_HOST=$HOST
ENV VITE_BACKEND_PORT=$BACKEND_PORT
RUN npm run build

FROM node:24-slim
COPY /frontend/package.json /frontend/package-lock.json /app/
COPY --from=prod-dep-env /app/node_modules /app/node_modules
COPY --from=build-env /app/build /app/build
WORKDIR /app
EXPOSE 3000
CMD ["npm", "run", "start"]
