name: Frontend CI

on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run linter
        run: |
          cd frontend
          npm run lint

      - name: Run prettier
        run: |
          cd frontend
          npx prettier --check .

      - name: Run Jest tests
        run: |
          cd frontend
          npm run test:coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: frontend/coverage
